name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      # 1. calcula versões
      - run: npx changeset version

      # 2. build (opcional mas recomendado)
      - run: npm run build

      # 3. cria commit de release
      - name: Commit version bump
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "chore: release" || exit 0
          git push

      # 4. cria tag + GitHub release
      - run: npx changeset tag